.TH suse-caasp-plugin "8" "09 Jun 2017" "suse-caasp-plugin" "Support Utilities Manual"
.SH NAME
suse-caasp-plugin \- SUSE Containers as a Platform Plugin for 
.BR supportconfig (8)
.
.SH DESCRIPTION
Supportconfig plugins add functionality to the supportconfig script. This plugin extends supportconfig's functionality to include SUSE Containers as a Platform information. Supportconfig saves the plugin output as plugin-suse_caasp.txt.

.SH FILES
.I /usr/lib/supportconfig/plugins/suse_caasp
.RS
The SUSE Containers as a Platform plugin
.RE
.SH AUTHOR
Containers Team <containers-bugowner@suse.de>
.SH REPORTING BUGS
Please submit bug fixes, comments or enhancement requests via: 
.B http://bugzilla.suse.com
.SH SEE ALSO
.BR supportconfig (8)
.BR supportconfig.conf (5)
